# Generated by Django 5.1.6 on 2025-08-24 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('dpo', 'DPO'), ('selcom', 'Selcom'), ('pesapal', 'PesaPal')], max_length=20, verbose_name='payment provider')),
                ('provider_ref', models.CharField(max_length=255, unique=True, verbose_name='provider reference')),
                ('method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('tigo_pesa', 'Tigo Pesa'), ('bank_transfer', 'Bank Transfer'), ('paypal_account', 'PayPal Account')], max_length=20, verbose_name='payment method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='exchange rate')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('provider_data', models.JSONField(blank=True, default=dict, verbose_name='provider data')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('failure_code', models.CharField(blank=True, max_length=50, verbose_name='failure code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('dpo', 'DPO'), ('selcom', 'Selcom'), ('pesapal', 'PesaPal')], max_length=20, verbose_name='provider')),
                ('method_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('tigo_pesa', 'Tigo Pesa'), ('bank_transfer', 'Bank Transfer'), ('paypal_account', 'PayPal Account')], max_length=20, verbose_name='method type')),
                ('provider_method_id', models.CharField(max_length=255, verbose_name='provider method ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('last_four', models.CharField(blank=True, max_length=4, verbose_name='last four digits')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='refund amount')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, verbose_name='provider refund ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15, verbose_name='status')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refund', to='orders.refund')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'db_table': 'payment_refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('dpo', 'DPO'), ('selcom', 'Selcom'), ('pesapal', 'PesaPal')], max_length=20, verbose_name='provider')),
                ('event_id', models.CharField(max_length=255, unique=True, verbose_name='event ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('raw_data', models.JSONField(verbose_name='raw webhook data')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('processing_attempts', models.PositiveIntegerField(default=0, verbose_name='processing attempts')),
                ('last_processing_error', models.TextField(blank=True, verbose_name='last processing error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'db_table': 'payment_webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_ref'], name='payments_provide_788e74_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_provide_2bfd66_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'provider_method_id')},
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['provider', 'event_type'], name='payment_web_provide_e7082c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['processed'], name='payment_web_process_d3b66c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['created_at'], name='payment_web_created_f9d7cb_idx'),
        ),
    ]
