# Generated by Django 5.1.6 on 2025-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.RenameField(
            model_name="paymentmethod",
            old_name="display_name",
            new_name="name",
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("provider", "method")},
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="allowed_countries",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of country codes where this method is available. Empty means all countries.",
                verbose_name="allowed countries",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific configuration (API keys, endpoints, etc.)",
                verbose_name="provider configuration",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fee as percentage (e.g., 3.5 for 3.5%)",
                max_digits=5,
                verbose_name="fee percentage",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="fixed_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Fixed fee amount in base currency",
                max_digits=10,
                verbose_name="fixed fee amount",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="icon_url",
            field=models.URLField(blank=True, verbose_name="icon URL"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="method",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("mpesa", "M-Pesa"),
                    ("airtel_money", "Airtel Money"),
                    ("tigo_pesa", "Tigo Pesa"),
                    ("bank_transfer", "Bank Transfer"),
                    ("paypal", "PayPal"),
                ],
                default="card",
                max_length=20,
                verbose_name="method",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="sort order"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="supported_currencies",
            field=models.JSONField(
                default=list,
                help_text='List of supported currency codes (e.g., ["USD", "TZS"])',
                verbose_name="supported currencies",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["provider", "method"], name="payment_met_provide_dca334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["is_active"], name="payment_met_is_acti_395fa6_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="last_four",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="method_type",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="provider_method_id",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="user",
        ),
    ]
