# Generated by Django 5.1.6 on 2025-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_payment_method_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("dpo", "DPO"),
                    ("selcom", "Selcom"),
                    ("pesapal", "PesaPal"),
                    ("azampay", "Azam Pay"),
                ],
                max_length=20,
                verbose_name="payment provider",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("dpo", "DPO"),
                    ("selcom", "Selcom"),
                    ("pesapal", "PesaPal"),
                    ("azampay", "Azam Pay"),
                ],
                max_length=20,
                verbose_name="provider",
            ),
        ),
        migrations.AlterField(
            model_name="paymentwebhook",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("dpo", "DPO"),
                    ("selcom", "Selcom"),
                    ("pesapal", "PesaPal"),
                    ("azampay", "Azam Pay"),
                ],
                max_length=20,
                verbose_name="provider",
            ),
        ),
    ]
