# Generated by Django 5.1.6 on 2025-08-24 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('template_file', models.FileField(upload_to='certificate_templates/', verbose_name='template file')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='certificate_previews/', verbose_name='preview image')),
                ('config', models.JSONField(default=dict, help_text='JSON configuration for template variables', verbose_name='template configuration')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Templates',
                'db_table': 'certificate_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=20, unique=True, verbose_name='serial number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('verified', 'Verified'), ('revoked', 'Revoked')], default='pending', max_length=10, verbose_name='status')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/', verbose_name='PDF certificate')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='certificates/qr/', verbose_name='QR code')),
                ('qr_url', models.URLField(blank=True, verbose_name='QR verification URL')),
                ('qr_data', models.JSONField(blank=True, default=dict, verbose_name='QR code data')),
                ('blockchain_network', models.CharField(blank=True, max_length=50, verbose_name='blockchain network')),
                ('token_id', models.CharField(blank=True, max_length=100, verbose_name='token ID')),
                ('contract_address', models.CharField(blank=True, max_length=100, verbose_name='contract address')),
                ('transaction_hash', models.CharField(blank=True, max_length=100, verbose_name='transaction hash')),
                ('issuer', models.CharField(default='SafariCrafts', max_length=200, verbose_name='issuer')),
                ('issued_to', models.CharField(blank=True, max_length=200, verbose_name='issued to')),
                ('issue_location', models.CharField(default='Tanzania', max_length=200, verbose_name='issue location')),
                ('verification_count', models.PositiveIntegerField(default=0, verbose_name='verification count')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='last verified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='issued at')),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='catalog.artwork')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='orders.order')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, verbose_name='referrer')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='verified at')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certificates.certificate')),
            ],
            options={
                'verbose_name': 'Certificate Verification',
                'verbose_name_plural': 'Certificate Verifications',
                'db_table': 'certificate_verifications',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['serial_number'], name='certificate_serial__ff4fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_a01db5_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['artwork'], name='certificate_artwork_a80514_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateverification',
            index=models.Index(fields=['certificate', 'verified_at'], name='certificate_certifi_fce4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateverification',
            index=models.Index(fields=['ip_address'], name='certificate_ip_addr_602327_idx'),
        ),
    ]
