# Generated by Django 5.1.6 on 2025-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzamPayAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(verbose_name="access token")),
                (
                    "refresh_token",
                    models.TextField(blank=True, verbose_name="refresh token"),
                ),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer", max_length=50, verbose_name="token type"
                    ),
                ),
                ("expires_in", models.DateTimeField(verbose_name="expires at")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "Azam Pay Auth Token",
                "verbose_name_plural": "Azam Pay Auth Tokens",
                "db_table": "azam_pay_auth_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
