# Generated by Django 5.1.6 on 2025-08-24 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='cover image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'collections',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='TZS', max_length=3, verbose_name='currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('story', models.TextField(blank=True, help_text='The story behind this artwork', verbose_name='story')),
                ('meaning', models.TextField(blank=True, verbose_name='cultural meaning')),
                ('tribe', models.CharField(blank=True, max_length=100, verbose_name='tribe')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('material', models.CharField(max_length=200, verbose_name='material')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('dimensions', models.CharField(help_text='L x W x H in cm', max_length=100, verbose_name='dimensions')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='weight in kg')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='TZS', max_length=3, verbose_name='currency')),
                ('stock_quantity', models.PositiveIntegerField(default=1, verbose_name='stock quantity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='draft', max_length=10, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('is_unique', models.BooleanField(default=True, verbose_name='is unique piece')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='attributes')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='like count')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artists.artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='catalog.category')),
                ('collections', models.ManyToManyField(blank=True, related_name='artworks', to='catalog.collection')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'db_table': 'artworks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('glb', '3D Model (GLB)'), ('usdz', '3D Model (USDZ)')], max_length=10, verbose_name='kind')),
                ('file', models.FileField(upload_to='artwork_media/', verbose_name='file')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artwork_thumbnails/', verbose_name='thumbnail')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='file size')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.artwork')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'artwork_media',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('snapshot', models.JSONField(default=dict, verbose_name='artwork snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.artwork')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
                'unique_together': {('cart', 'artwork')},
            },
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['artist', 'status'], name='artworks_artist__090178_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category', 'status'], name='artworks_categor_fc3114_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['tribe', 'region'], name='artworks_tribe_9e6e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['price', 'currency'], name='artworks_price_d5c3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['created_at'], name='artworks_created_917985_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['is_featured', 'status'], name='artworks_is_feat_2b7051_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['artwork', 'kind'], name='artwork_med_artwork_fb0141_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['is_primary'], name='artwork_med_is_prim_3891d6_idx'),
        ),
    ]
