# Generated by Django 5.1.6 on 2025-08-27 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_artworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="likes",
            ),
        ),
    ]
