# Generated by Django 5.1.6 on 2025-08-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('tribe', models.CharField(blank=True, max_length=100, verbose_name='tribe')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=10, verbose_name='KYC status')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram handle')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook page')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter handle')),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='kyc/ids/', verbose_name='ID document')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='ID number')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='bank name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='bank account number')),
                ('mobile_wallet_number', models.CharField(blank=True, max_length=20, verbose_name='mobile wallet number')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total sales')),
                ('total_artworks', models.PositiveIntegerField(default=0, verbose_name='total artworks')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='TZS', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10, verbose_name='status')),
                ('provider', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='provider')),
                ('provider_ref', models.CharField(blank=True, max_length=255, verbose_name='provider reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'db_table': 'artist_payouts',
            },
        ),
    ]
