# Generated by Django 5.1.6 on 2025-08-24 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='payout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['tribe', 'region'], name='artists_tribe_70be9f_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['kyc_status'], name='artists_kyc_sta_b0542b_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['artist', 'status'], name='artist_payo_artist__304f26_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['created_at'], name='artist_payo_created_41f3c1_idx'),
        ),
    ]
