# Generated by Django 5.1.6 on 2025-08-24 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('carrier', models.CharField(max_length=50, verbose_name='carrier')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='base cost')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='cost per kg')),
                ('min_delivery_days', models.PositiveIntegerField(verbose_name='minimum delivery days')),
                ('max_delivery_days', models.PositiveIntegerField(verbose_name='maximum delivery days')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='max weight (kg)')),
                ('max_dimensions', models.CharField(blank=True, max_length=50, verbose_name='max dimensions (LxWxH cm)')),
                ('domestic_only', models.BooleanField(default=True, verbose_name='domestic only')),
                ('supported_countries', models.JSONField(blank=True, default=list, verbose_name='supported countries')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'db_table': 'shipping_methods',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(max_length=50, verbose_name='carrier')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='tracking number')),
                ('label_url', models.URLField(blank=True, verbose_name='shipping label URL')),
                ('label_format', models.CharField(default='PDF', max_length=10, verbose_name='label format')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='weight (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='dimensions (LxWxH cm)')),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='declared value')),
                ('from_address', models.JSONField(verbose_name='from address')),
                ('to_address', models.JSONField(verbose_name='to address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('labeled', 'Label Created'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='shipping cost')),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='insurance cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('delivered_to', models.CharField(blank=True, max_length=200, verbose_name='delivered to')),
                ('delivery_signature', models.CharField(blank=True, max_length=200, verbose_name='delivery signature')),
                ('delivery_photo_url', models.URLField(blank=True, verbose_name='delivery photo URL')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingmethod')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2, verbose_name='country')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('min_weight', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='minimum weight (kg)')),
                ('max_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='maximum weight (kg)')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='base rate')),
                ('per_kg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='per kg rate')),
                ('service_level', models.CharField(default='standard', max_length=50, verbose_name='service level')),
                ('min_delivery_days', models.PositiveIntegerField(verbose_name='minimum delivery days')),
                ('max_delivery_days', models.PositiveIntegerField(verbose_name='maximum delivery days')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'db_table': 'shipping_rates',
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50, verbose_name='event type')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('occurred_at', models.DateTimeField(verbose_name='occurred at')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('source', models.CharField(default='carrier', max_length=50, verbose_name='source')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='raw event data')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Event',
                'verbose_name_plural': 'Shipment Events',
                'db_table': 'shipment_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['shipment', 'occurred_at'], name='shipment_ev_shipmen_5da00d_idx'), models.Index(fields=['event_type'], name='shipment_ev_event_t_f6b5a1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipments_trackin_cc256d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_status_cda325_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['carrier', 'status'], name='shipments_carrier_fd96da_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['country', 'service_level'], name='shipping_ra_country_2e0309_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['shipping_method', 'country'], name='shipping_ra_shippin_af293c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('shipping_method', 'country', 'service_level', 'min_weight', 'max_weight')},
        ),
    ]
